#!/bin/bash
# ---------------------------------------------------------------------
# Written for CrunchBang Linux <http://crunchbang.org/>
# by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
# ---------------------------------------------------------------------


# In order to add another browser, simply add it to this array:
TOOLS=('chromium' 'firefox' 'opera')

if ! . cb-include.cfg 2> /dev/null; then
    say 'Failed to locate cb-include.cfg in PATH' >&2
    exit 1
fi

browserExists() {
    for curTool in "${TOOLS[@]}"; do # if $packageName exists in tools array
        [[ $curTool = "$1" ]] &&
            return 0
    done
    say "Unable to install $1. There is no such browser that I know of." >&2
    say "You can try one of these: ${TOOLS[@]}" >&2
    return 1
}

if [[ $1 && ! $1 =~ --install-* ]]; then
    browserExists "${1:2}" || exit 1
    browserName=${1:2}
    browserName=${browserName//-/ }
    terminator --title="Install ${browserName~}" --command="cb-x-www-browser-pipemenu --install-${1:2}"

elif [[ $1 = --install-* ]]; then
    packageName=${1#--install-}
    browserName=${packageName//-/ }
    browserName=${browserName~}
    browserNameUpper=${browserName^^}

    browserExists "$packageName" || exit 1

    while true; do # do it until the package is successfully installed or user wants to exit
        if [[ $TRYAGAIN ]]; then # previous try failed
            say
            say "There was a problem installing $browserName."
            say
            prompt '  Hit any key to try again, or "q" to quit...' Q && break
        fi
        TRYAGAIN=true

        clear
        say
        say "INSTALL ${browserNameUpper% BROWSER} BROWSER"
        say '------------------------'
        say "This script will install $browserName."
        say
        prompt '  Run the installer now?' || break

        clear
        connectiontest 1 || continue

        setupFunctionName="setup${browserName//[^a-zA-Z]/}" # setupFunctionName should now be in format like 'setupChromiumBrowser'
        if [[ $(type -t "$setupFunctionName") == 'function' ]]; then
            "$setupFunctionName" || continue # run setup function if it exists
        fi

        clear
        say 'Updating sources...' 1
        sudo pacman -Sy

        clear
        say 'Installing package...' 1
        sudo pacman --noconfirm -S "$packageName" || continue

        clear
        say
        say "$browserName has been installed successfully."
        say
        say 'Hit any key to exit...'
        read -srn1
        break
    done
else # pipemenu
    menuStart
    for curTool in "${TOOLS[@]}"; do
        curToolName=${curTool//-/ }
        curToolName=${curToolName~}
        if type "$curTool" &> /dev/null; then
            INSTALLED=true
            menuItem "$curToolName" "$curTool"
            [[ $curToolName =~ 'Chrom' ]] &&
                menuItem "$curToolName (Private Mode)" "$curTool --incognito" # Incognito mode for chrome and chromium
        else
            menuItem "Install $curToolName" "cb-x-www-browser-pipemenu --$curTool"
        fi
    done

    if [[ $INSTALLED ]]; then
        menuSeparator
        menuItem 'Select default browser' 'terminator --command="sudo update-alternatives --config x-www-browser"'
    fi
    menuEnd
fi
exit 0
